## Here to start to write my first deployment file in my Zero_Project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapi
  template: 
      metadata: 
        labels:
	  app: testapi
      spec: 
	    containers:
	      - name: main-container
	      image: ghcr.io/BaiterYu0101/testapi: latest
	      ports:
	      - containerPort: 8000
          

