## Here to start to write my first deployment file in my Zero_Project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final
  template: 
      metadata: 
        labels:
	  app: final
      spec: 
	    containers:
	      - name: main-container
	      image: ghcr.io/BaiterYu0101/final: latest
	      ports:
	      - containerPort: 8000
          

