## Here to start to write my first deployment file in my Zero_Project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3-api-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test3-api-app
  template: 
      metadata: 
        labels:
	  app: test3-api-app
      spec: 
	    containers:
	      - name: main-container
	      image: ghcr.io/BaiterYu0101/test3-api-app: latest
	      ports:
	      - containerPort: 8000
          

